<?php

namespace Defr;

/**
 * Class NameDays
 * @package Defr
 * @author Dennis Fridrich <fridrich.dennis@gmail.com>
 */
class NameDays
{
    /**
     * @var array
     */
    private static $data = [
        1 => [
            1 => '!Nový rok',
            'Karina',
            'Radmila',
            'Diana',
            'Dalimil',
            '!Tři králové',
            'Vilma',
            'Čestmír',
            'Vladan',
            'Břetislav',
            'Bohdana',
            'Pravoslav',
            'Edita',
            'Radovan',
            'Alice',
            'Ctirad',
            'Drahoslav',
            'Vladislav',
            'Doubravka',
            'Ilona',
            'Běla',
            'Slavomír',
            'Zdeněk',
            'Milena',
            'Miloš',
            'Zora',
            'Ingrid',
            'Otýlie',
            'Zdislava',
            'Robin',
            'Marika',
        ],
        [
            1 => 'Hynek',
            'Nela',
            'Blažej',
            'Jarmila',
            'Dobromila',
            'Vanda',
            'Veronika',
            'Milada',
            'Apolena',
            'Mojmír',
            'Božena',
            'Slavěna',
            'Věnceslav',
            'Valentýn',
            'Jiřina',
            'Ljuba',
            'Miloslava',
            'Gizela',
            'Patrik',
            'Oldřich',
            'Lenka',
            'Petr',
            'Svatopluk',
            'Matěj',
            'Liliana',
            'Dorota',
            'Alexandr',
            'Lumír',
            'Horymír',
        ],
        [
            1 => 'Bedřich',
            'Anežka',
            'Kamil',
            'Stela',
            'Kazimír',
            'Miroslav',
            'Tomáš',
            'Gabriela',
            'Františka',
            'Viktorie',
            'Anděla',
            'Řehoř',
            'Růžena',
            'Root/Matylda',
            'Ida',
            'Elena/Herbert',
            'Vlastimil',
            'Eduard',
            'Josef',
            'Světlana',
            'Radek',
            'Leona',
            'Ivona',
            'Gabriel',
            'Marián',
            'Emanuel',
            'Dita',
            'Soňa',
            'Taťána',
            'Arnošt',
            'Kvido',
        ],
        [
            1 => 'Hugo',
            'Erika',
            'Richard',
            'Ivana',
            'Miroslava',
            'Vendula',
            'Heřman/Hermína',
            'Ema',
            'Dušan',
            'Darja',
            'Izabela',
            'Julius',
            'Aleš',
            'Vincenc',
            'Anastázie',
            'Irena',
            'Rudolf',
            'Valérie',
            'Rostislav',
            'Marcela',
            'Alexandra',
            'Evženie',
            'Vojtěch',
            'Jiří',
            'Marek',
            'Oto',
            'Jaroslav',
            'Vlastislav',
            'Robert',
            'Blahoslav',
        ],
        [
            1 => '!Svátek práce',
            'Zikmund',
            'Alexej',
            'Květoslav',
            'Klaudie',
            'Radoslav',
            'Stanislav',
            '!Den osvobození',
            'Ctibor',
            'Blažena',
            'Svatava',
            'Pankrác',
            'Servác',
            'Bonifác',
            'Žofie',
            'Přemysl',
            'Aneta',
            'Nataša',
            'Ivo',
            'Zbyšek',
            'Monika',
            'Emil',
            'Vladimír',
            'Jana',
            'Viola',
            'Filip',
            'Valdemar',
            'Vilém',
            'Maxmilián',
            'Ferdinand',
            'Kamila',
        ],
        [
            1 => 'Laura',
            'Jarmil',
            'Tamara',
            'Dalibor',
            'Dobroslav',
            'Norbert',
            'Iveta/Slavoj',
            'Medard',
            'Stanislava',
            'Gita',
            'Bruno',
            'Antonie',
            'Antonín',
            'Roland',
            'Vít',
            'Zbyněk',
            'Adolf',
            'Milan',
            'Leoš',
            'Květa',
            'Alois',
            'Pavla',
            'Zdeňka',
            'Jan',
            'Ivan',
            'Adriana',
            'Ladislav',
            'Lubomír',
            'Petr/Pavel',
            'Šárka',
        ],
        [
            1 => 'Jaroslava',
            'Patricie',
            'Radomír',
            'Prokop',
            '!Cyril a Metoděj',
            '!Jan Hus',
            'Bohuslava',
            'Nora',
            'Drahoslava',
            'Libuše/Amálie',
            'Olga',
            'Bořek',
            'Markéta',
            'Karolína',
            'Jindřich',
            'Luboš',
            'Martina',
            'Drahomíra',
            'Čeněk',
            'Ilja',
            'Vítězslav',
            'Magdaléna',
            'Libor',
            'Kristýna',
            'Jakub',
            'Anna',
            'Věroslav',
            'Viktor',
            'Marta',
            'Bořivoj',
            'Ignác',
        ],
        [
            1 => 'Oskar',
            'Gustav',
            'Miluše',
            'Dominik',
            'Kristián',
            'Oldřiška',
            'Lada',
            'Soběslav',
            'Roman',
            'Vavřinec',
            'Zuzana',
            'Klára',
            'Alena',
            'Alan',
            'Hana',
            'Jáchym',
            'Petra',
            'Helena',
            'Ludvík',
            'Bernard',
            'Johana',
            'Bohuslav',
            'Sandra',
            'Bartoloměj',
            'Radim',
            'Luděk',
            'Otakar',
            'Augustýn',
            'Evelína',
            'Vladěna',
            'Pavlína',
        ],
        [
            1 => 'Linda/Samuel',
            'Adéla',
            'Bronislav',
            'Jindřiška',
            'Boris',
            'Boleslav',
            'Regína',
            'Mariana',
            'Daniela',
            'Irma',
            'Dennis/Denisa',
            'Marie',
            'Lubor',
            'Radka',
            'Jolana',
            'Ludmila',
            'Naděžda',
            'Kryštof',
            'Zita',
            'Oleg',
            'Matouš',
            'Darina',
            'Berta',
            'Jaromír',
            'Zlata',
            'Andrea',
            'Jonáš',
            'Václav',
            'Michal',
            'Jeroným',
        ],
        [
            1 => 'Igor',
            'Olívie/Oliver',
            'Bohumil',
            'František',
            'Eliška',
            'Hanuš',
            'Justýna',
            'Věra',
            'Štefan/Sára',
            'Marina',
            'Andrej',
            'Marcel',
            'Renáta',
            'Agáta',
            'Tereza',
            'Havel',
            'Hedvika',
            'Lukáš',
            'Michaela',
            'Vendelín',
            'Brigita',
            'Sabina',
            'Teodor',
            'Nina',
            'Beáta',
            'Erik',
            'Šarlota/Zoe',
            '!Státní svátek',
            'Silvie',
            'Tadeáš',
            'Štěpánka',
        ],
        [
            1 => 'Felix',
            '!Památka zesnulých',
            'Hubert',
            'Karel',
            'Miriam',
            'Liběna',
            'Saskie',
            'Bohumír',
            'Bohdan',
            'Evžen',
            'Martin',
            'Benedikt',
            'Tibor',
            'Sáva',
            'Leopold',
            'Otmar',
            'Mahulena',
            'Romana',
            'Alžběta',
            'Nikola',
            'Albert',
            'Cecílie',
            'Klement',
            'Emílie',
            'Kateřina',
            'Artur',
            'Xenie',
            'René',
            'Zina',
            'Ondřej',
        ],
        [
            1 => 'Iva',
            'Blanka',
            'Svatoslav',
            'Barbora',
            'Jitka',
            'Mikuláš',
            'Benjamín',
            'Květoslava',
            'Vratislav',
            'Julie',
            'Dana',
            'Simona',
            'Lucie',
            'Lýdie',
            'Radana/Radan',
            'Albína',
            'Daniel',
            'Miloslav',
            'Ester',
            'Dagmar',
            'Natálie',
            'Šimon',
            'Vlasta',
            'Adam/Eva',
            '!1. svátek vánoční',
            'Štěpán',
            'Žaneta',
            'Bohumila',
            'Judita',
            'David',
            'Silvestr',
        ],
    ];

    /**
     * @param \DateTime $date
     *
     * @return string
     */
    public static function getNameDay(\DateTime $date = null)
    {
        if (!$date) {
            $date = new \DateTime();
        }
        $name = self::$data[$date->format('n')][$date->format('j')];
        if ($name[0] != '!') {
            $return = $name;
        } else {
            $return = substr($name, 1);
        }

        return $return;
    }

    /**
     * @param $name
     * @return \DateTime|null
     */
    public static function getNameDate($name)
    {
        $matches = [];
        for ($i = 1; $i <= 12; $i++) {
            foreach (self::$data[$i] as $day => $value) {
                $check = mb_stripos($value, $name);
                if (false !== $check) {
                    $matches[] = [$i, $day, $value, levenshtein($name, $value)];
                }
            }
        }

        usort(
            $matches,
            function ($a, $b) {
                return $a[3] > $b[3];
            }
        );

        if (count($matches) == 0) {
            return null;
        }

        $date = new \DateTime();
        $date->setDate(date("Y"), $matches[0][0], $matches[0][1]);

        return $date;
    }
}
